# -*- coding: utf-8 -*-
"""Assignment_PR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8lL4KmEHk4FoaMM42s2ZO1-Yl9sEiGV
"""

#Creating a list
list1 = [1, 2, 3, "Souvik", "Adhikary", "MAKAUT"]

#a) insert()
list1.insert(5, 5)

#printing new list
print(list1)

#b) remove()
list1.remove(5)

#printing new list
print(list1)

#c) append()
list1.append(6)

#printing new list
print(list1)

#d) len()
len(list1)

#e) pop()
list1.pop(0)

#printing new list
print(list1)

#f) clear()
list1.clear()

#priting list now
print(list1)

#python program to take in the marks of 5 subjects and display the grade
sub1 = int(input("Enter the marks of first subject: "))
sub2 = int(input("Enter the marks of second subject: "))
sub3 = int(input("Enter the marks of third subject: "))
sub4 = int(input("Enter the marks of fourth subject: "))
sub5 = int(input("Enter the marks of fifth subject: "))

tot = sub1+sub2+sub3+sub4+sub5
avg = tot/5

if (avg >= 90):
  print("Student grade is A")
elif (avg >= 80 and avg < 90):
  print("Student grade is B")
elif (avg >= 70 and avg < 80):
  print("Studnet grade is C")
elif (avg >= 60 and avg < 70):
  print("studnet grade is D")
elif (avg >= 35 and avg < 60):
  print("Student grade is E")
else:
  print("Student failed")

#Python program to reverse a given number
n = int(input("Enter number: "))
rev = 0
while (n > 0):
    dig = n%10
    rev = rev * 10 + dig
    n = n//10
print("Reverse of the number:", rev)

#Python program to read a number n and compute n+nn+nnn.......
n = int(input("Enter a number n: "))
temp = str(n)
t1 = temp+temp
t2 = temp+temp+temp
t3 = temp+temp+temp+temp
t4 = temp+temp+temp+temp+temp
comp = n + int(t1) + int(t2) + int(t3) + int(t4)
print("The value is:",comp)

#Write a python program to print date, time for today and now.
import datetime
now = datetime.datetime.now()
print("Time for today and now: ")
print(now.strftime("%d-%m-%Y %H:%M:%S"))

#Using a numpy module creating an array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#a)type of array
print(type(arr))

#b)axes of array
import numpy as np
np_array = np.arange(0, 8).reshape([4, 2])
print(np_array)

#one more type of axis 
import numpy as np
np_array1 = np.arange(0, 10).reshape(2, 5)
print(np_array1)

#c)shape of array
import numpy as np
arr1 = np.array([[1,2.3,"Adhikary"], [4.1,5,"Souvik"]])
print(arr1.shape)

#D)Types of element in array
import numpy as np
element = np.array([1, 2, 3])
print(element.dtype)