# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fidGRNaAWIDQlABQHiEMs-f_69cqD_Wp
"""

#1.Create a string and print its length using len().
new_str = str("Souvik")
print(len(new_str))

#2.Create two strings, concatenate them, and print the resulting string.
str1 = str("Souvik")
str2 = str("Adhikary")
print(str1, str2)

#3.Write a program that converts the following strings to lowercase:
text1 = "Animals"
print(text1.lower())
text2 = "Badger"
print(text2.lower())
text3 = "Honey Bee"
print(text3.lower())
text4 = "Honey Badger"
print(text4.lower())

#4.Write a program that takes input from the user and displays
#the number of characters in the input.
text = input("Enter string:")
len(text)

#5.Create a function that finds the average of two numbers.
def average(a, b):
  return (a+b)/2

num1 = float(input("Enter the first number:"))
num2 = float(input("Enter the second number"))

avg = average(num1, num2)

print("average of two numbers = %.2f" %avg)

#6.Create a Function that Implements prime numbers.
num = int(input("Enter the number:"))
def is_prime(num):
  if(num <= 1):
    return False
  for i in range(2, num):
    if(num % i) == 0:
      return False
  return True

if(is_prime(num)):
  print(num, "is a prime number")
else:
  print(num, "is not a prime number")

